### ISSUE TITLE
Pequena esclarecimento sobre o exercício

### ISSUE THREAD

**Issue by ZeMaheli** [premium-minds/summer-internship-exercise-2024#2]
Gostava só de confirmar se o objetivo é retornar qualquer coisa como "father of X ; father of Y; grandfather of Z ..." tudo numa string, para a pessoa que é passada como argumento na função.

**Comment by amadoandre** [comment]
é para retornar apenas o tecnónimo , No exemplo do exercicio mosta  isso ( com o caso do A , em que ele é pai e avô mas o tecnónimo é só avô)  . o objectivo é retornar apenas a representação face ao mais velhos da maior linha familiar
